name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        # run: go test -json ./... > test-results.json
        run: go test ./...
      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: test-results.json
  lint:
    permissions:
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      # pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
